const UPDATE_INTERVAL = 200;
const GRID_SPACE = 1;
const CELL_SIZE = 10;
//const GRID_WIDTH = 100;
//const GRID_HEIGHT = 50;

export { UPDATE_INTERVAL, GRID_SPACE, CELL_SIZE}//, GRID_WIDTH, GRID_HEIGHT };